name:                Libil
version:             0.1.0.0
github:              "ibnuda/Libil"
license:             BSD3
author:              "Ibnu D. Aji"
maintainer:          "ibnudaruaji@outlook.co.id"
copyright:           "2018 Ibnu D. Aji"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ibnuda/Libil#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text

library:
  source-dirs: src

tests:
  Libil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Libil
